title ModeloDeDominio_UML_Clases

@startuml DomainModel

class Usuario {
  -ID: String
  -Nombre: String
  -EmailInstitucional: String
  -Foto: Image
  -Estado: Boolean

  +crearPublicacion()
  +participarEvento()
  +recibirNotificacion()
}

class Moderador {
  -nivelPermisos: int
  -areaModeracion: String

  +aprobarPublicacion()
  +moderarComentarios()
  +gestionarEventos()
}

class Estudiante {
}

class Profesor {
  +crearEvento()
}

class PersonalApoyo {
  +realizarTareasApoyo()
}

class Facultad {
  -ID: String
  -Nombre: String
  -Descripcion: String
  -Ubicacion: String
}

class Carrera {
  -ID: String
  -Nombre: String
  -Descripcion: String
  -Coordinador: String
}

class Evento {
  -ID: String
  -Titulo: String
  -Descripcion: String
  -FechaHora: DateTime
  -Tipo: String
  -Estado: String
}

class Notificacion {
  -ID: String
  -Contenido: String
  -Fecha: DateTime
  -Tipo: String
  -Estado: String
}

class Espacio {
  -ID: String
  -Nombre: String
  -Tipo: String
  -Capacidad: int
  -Disponibilidad: Boolean
}

class Publicacion {
  -ID: String
  -Titulo: String
  -Contenido: String
  -Fecha: DateTime
  -Estado: String
  -Tipo: String
}

class Comentario {
  -ID: String
  -Contenido: String
  -Fecha: DateTime
  -Estado: String
}

' Relaciones
Moderador -up-|> Usuario
Profesor -up-|> Usuario
Estudiante -right-|> Usuario
PersonalApoyo -up-|> Usuario

Usuario "1" -up- "*" Publicacion: crea >
Usuario "1" -up- "*" Evento: participa >
Usuario "1" -up- "*" Notificacion: recibe >

Estudiante "*" -up- "1...2" Carrera: cursa >

Facultad "1" *-down- "n" Carrera: tiene >
Facultad "1" *-down- "*" Usuario: contiene >
Facultad "1" *-up- "*" Espacio: alberga >

Evento "*" -down- "1" Usuario: creado por >
Evento "*" -left- "1" Espacio: se realiza en >
Evento "1" -- "*" Publicacion: genera >

Publicacion "1" -- "0...*" Comentario: tiene >
Publicacion "1" -- "0...*" Notificacion: genera >

Comentario "*" -down- "1" Usuario: creado por >

@enduml